<?php

namespace Drupal\migratedata\Plugin\migrate\source;

use Drupal\migrate\Event\MigrateRollbackEvent;
use Drupal\migrate\Plugin\migrate\source\SqlBase;
use Drupal\migrate\Row;

/**
 *  Extract users from Drupal 7 database.
 *
 * @MigrateSource(
 *   id = "custom_user"
 * )
 */
class User extends SqlBase {

  public function query() {
    $fields = [
      'aid',
      'status',
      'registered',
      'username',
      'nickname',
      'password',
      'email',
    ];

    return $this->select('wordpress_user_table', 'wut')->fields('wut', $fields);
  }

  public function fields() {
    $fields = [
      'aid' => $this->t('Account ID'),
      'status' => $this->t('Blocked/Allowed'),
      'registered' => $this->t('Registered date'),
      'username' => $this->t('Account name (for login)'),
      'nickname' => $this->t('Account name (for display)'),
      'password' => $this->t('Account password (raw)'),
      'email' => $this->t('Account email'),
      'sex' => $this->t('Gender'),
    ];

    return $fields;
  }

  public function getIds() {
    return [
      'aid' => [
        'type' => 'integer',
        'alias' => 'wut',
      ],
    ];
  }

  public function prepareRow(Row $row) {

    $password = $row->getSourceProperty('password');
    $hash = \Drupal::service('password')->hash($password);
    $row->setSourceProperty('password', $hash);
    //return parent::prepareRow($row); // TODO: Change the autogenerated stub
  }

  public function preRollback(MigrateRollbackEvent $event) {
    //parent::preRollback($event); // TODO: Change the autogenerated stub
  }

  public function postRollback(MigrateRollbackEvent $event) {
    //parent::postRollback($event); // TODO: Change the autogenerated stub
  }

}