<?php
/**
 * Created by PhpStorm.
 * User: Arul
 * Date: 7/7/2018
 * Time: 8:01 AM
 */

namespace Drupal\learning\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Provides a 'CustomBlock' block.
 *
 * @Block(
 *  id = "custom_block",
 *  admin_label = @Translation("Custom block"),
 * )
 */
class CustomBlock extends BlockBase {

  public function defaultConfiguration() {
    return ['company_name' => ''];
    // return parent::defaultConfiguration(); // TODO: Change the autogenerated stub
  }

  public function blockForm($form, FormStateInterface $form_state) {
    $form['company_name'] = [
      '#type' => 'textfield',
      '#title' => t('Company name'),
      '#default_value' => $this->configuration['company_name'],
    ];
    return $form;
  }

  public function blockSubmit($form, FormStateInterface $form_state) {
    $this->configuration['company_name'] = $form_state->getValue('company_name');
  }

  public function build() {
    $date = new \DateTime();
    return [
      '#markup' => t('Copyright @year&copy; @company', [
        '@year' => $date->format('Y'),
        '@company' => $this->configuration['company_name'],
      ]),
    ];
  }

  public function blockAccess(AccountInterface $account) {

    /*$route_name = $this->routeMatch->getRouteName();
    if ($account->isAnonymous() && !in_array($route_name,
        ['user.login', 'user.logout'])) {
      return AccessResult::allowed()
        ->addCacheContexts([
          'route.name',
          'user.roles:anonymous',
        ]);
    }*/
    return \Drupal\Core\Access\AccessResult::forbidden();
  }

}