<?php
/**
 * Created by PhpStorm.
 * User: Arul
 * Date: 6/23/2018
 * Time: 8:43 PM
 */

namespace Drupal\Learning\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SampleSettingForm extends ConfigFormBase {

  public function getFormId() {
    // TODO: Implement getFormId() method.
    return 'sample-setting-form';
  }

  public function getEditableConfigNames() {
    return [
      'learning.samplesettings',
    ];
    // TODO: Implement getEditableConfigNames() method.
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('learning.samplesettings');

    $form['stextfield'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Textfield'),
      '#description' => $this->t('Enter CEO uid here'),
      '#maxlength' => 10,
      '#size' => 64,
      '#default_value' => $config->get('stextfield'),
    ];
    $form['stextarea'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Grid Enables'),
      '#description' => $this->t('Enter url on new line to enable 12 grid options'),
      '#default_value' => $config->get('stextarea'),
    ];
    $form['scheckbox'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Checkbox'),
      '#default_value' => $config->get('scheckbox'),
    ];
    $form['scheckboxes'] = [
      '#type' => 'checkboxes',
      '#title' => $this->t('Checkboxes'),
      '#options' => ['SAT' => 'SAT', 'ACT' => 'ACT'],
      '#default_value' => $config->get('scheckboxes'),
    ];
    $form['sdate'] = [
      '#type' => 'date',
      '#title' => $this->t('Date'),
      '#default_value' => $config->get('sdate'),
    ];
    $form['sradio'] = [
      '#type' => 'radio',
      '#title' => $this->t('Radio'),
      '#default_value' => $config->get('sradio'),
    ];
    $form['srange'] = [
      '#type' => 'range',
      '#title' => $this->t('Range'),
      '#default_value' => $config->get('srange'),
    ];
    $form['semail'] = [
      '#type' => 'email',
      '#title' => $this->t('Email'),
      '#default_value' => $config->get('semail'),
    ];
    $form['stel'] = [
      '#type' => 'tel',
      '#title' => $this->t('Tel'),
      '#default_value' => $config->get('stel'),
    ];
    $form['scolor'] = [
      '#type' => 'color',
      '#title' => $this->t('Color'),
      '#default_value' => $config->get('scolor'),
    ];
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {

    $this->config('learning.samplesettings')
      ->set('stextfield', $form_state->getValue('stextfield'))
      ->set('stextarea', $form_state->getValue('stextarea'))
      ->set('scheckbox', $form_state->getValue('scheckbox'))
      ->set('scheckboxes', $form_state->getValue('scheckboxes'))
      ->set('sdate', $form_state->getValue('sdate'))
      ->set('sradio', $form_state->getValue('sradio'))
      ->set('srange', $form_state->getValue('srange'))
      ->set('semail', $form_state->getValue('semail'))
      ->set('stel', $form_state->getValue('stel'))
      ->set('scolor', $form_state->getValue('scolor'))
      ->save();

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}