<?php

/**
 * @file
 * Contains learning.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function learning_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the learning module.
    case 'help.page.learning':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('I have started new module to learn drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function learning_theme() {
  return [
    'learning' => [
      'render element' => 'children',
      'variables' => ['test_var' => NULL],
    ],
  ];
}


function learning_block_alter(&$definitions) {
  $definitions['custom_block']['admin_label'] = t('Custom Block Updates');
}

/**
 * Implements hook_block_build_alter().
 */
function learning_block_build_alter(array &$build, BlockPluginInterface $block) {

  if ($block->getBaseId() == 'custom_block') {
    $build['#cache']['contexts'][] = 'user';
  }
}

/**
 * Implements hook_block_build_BASE_BLOCK_ID_alter().
 */
function learning_block_build_custom_block_alter(array &$build, BlockPluginInterface $block) {
  drupal_set_message($block->getPluginId());
}

/**
 * Implements hook_block_view_alter().
 */
function learning_block_view_alter(array &$build, BlockPluginInterface $block) {
  if (isset($build['#contextual_links'])) {
    //unset($build['#contextual_links']); if we enabled it will remove the Edit links
  }
}

/**
 * Implements hook_block_access().
 */
function learning_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if ($block->getPluginId() == 'learning_config_block') {
    //return \Drupal\Core\Access\AccessResult::forbidden();
  }

}

function learning_node_presave(EntityInterface $node) {
 // echo '<pre>';
  //echo $node_type = $node->getType();
  //print_r($node->field_domain_access->getValue());
  //die('dfd');
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function learning_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change form id here
  //kint($form);

  $form['#validate'][] = 'domain_access_form_validate';
  // Custom Submit function.
  $form['actions']['submit']['#submit'][] = 'faq_ask_submit';
}

function domain_access_form_validate($form, FormStateInterface &$form_state) {
  //echo '<pre>';
  $values = $form_state->getValues();
  $access_value = $form_state->getValues('arulraj');
  $new_values = (is_array($access_value)) ? explode(',', $access_value) : '';
  if (empty($new_values)) {
    //$form_state->setErrorByName('arulraj', t('The Domain name field is required.'));
  }
  //print_r($values);
  //echo $email = $form_state->getValue('arulraj');
  //die;
}

function faq_ask_submit($form, FormStateInterface $form_state) {
  $user = \Drupal::currentUser();
  if ($user->hasPermission('ask question') && !$user->hasPermission('answer question')) {
    $node_id = $form_state->getValue('nid');
    $node = node_load($node_id);
    if (is_object($node)) {
      $access_value = $form_state->getValues('arulraj');
      $new_value = explode(',', $access_value);
      foreach ($new_value as $value) {
        $node->field_code_used_by[] = ['target_id' => $user_id];
      }
      $node->save();
    }
  }
}